{{- $fullName := .Values.appName -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-service-beta
  labels:
    app: {{ template "blue-green.name" . }}
    chart: {{ template "blue-green.chart" . }}
    release: {{ $fullName }}
spec:
  type: NodePort
  ports:
    - port: 9080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "blue-green.name" . }}
    release: {{ $fullName }}
    {{- if eq .Values.productionSlot "blue" }}
    slot: green
    {{- else }}
    slot: blue
    {{- end }}
